### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by makixGRA** [bradleyfay/spoRts#3]
I have this problem.

`Installing package into ‘/home/miguel/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
* installing *source* package ‘spoRts’ ...
** R
** preparing package for lazy loading
Error in eval(expr, envir, enclos) : 
  no se pudo encontrar la función "get_season"
Error : unable to load R code in package ‘spoRts’
ERROR: lazy loading failed for package ‘spoRts’
* removing ‘/home/miguel/R/x86_64-pc-linux-gnu-library/3.2/spoRts’
Error in i.p(...) : 
  (convertido del aviso) installation of package ‘/tmp/RtmppLYp67/file70733772e475/spoRts_0.1.0.tar.gz’ had non-zero exit status`

How can I fix this?

**Comment by bradleyfay** [comment]
I don't really have this module in a place where it's ready to be installed. I started scaffolding out code and then the work got deprioritized.

Sorry :(
